import { CustomerDto } from "../data-transfer-objects/order-entry-dtos";


export class Customer {
    accountDivision: string;
    companyCode: number;
    customerNumber: number;
    customerName: string;
    addressLine1: string;
    addressLine2: string;
    addressLine3: string;
    addressLine4: string;
    zipCode5: string;
    zipCode9: string;
    zipCode14: string;
    totalDue: number;
    currentDue: number;
    overdue1To10Days: number;
    overdue11To20Days: number;
    overdue21To30Days: number;
    overdueOver30Days: number;
    lastPaymentAmount: number;
    lastPaymentDate: string;
    prepaidAmount: number;
    monthToDateSales: number;
    yearToDateSales: number;
    statementFlag: string;
    financialAdjustmentFlag: string;
    previousBalance: number;
    financialIncrease: number;
    monthlyCreditPeriod: number;
    yearlyCreditPeriod: number;
    creditLimit: number;
    areaCode: number;
    telephoneNumber: string;
    salesPersonNumber: number;
    termsCode: number;
    stateTaxCode: string;
    lastTransactionNumber: number;
    groupCode: string;
    miles: number;
    highBalance: number;
    highBalanceDate: string;
    interestRate: number;
    accountStatus: string;
    referenceNumber: string;
    groupCompany: string;
    groupCustomerNumber: number;
    paymentDate8Digit: string;
    highBalanceDate8Digit: string;
    customerClass: string;
    ediIndicator: string;
    closeBalance: number;
    wireTransferFlag: string;
    federalEIN: string;
    paymentClass: string;
    promotionalCode: string;
    reservedField1: string;

    constructor(dto: CustomerDto) {
        this.accountDivision = dto.accountDivision;
        this.companyCode = dto.companyCode;
        this.customerNumber = dto.customerNumber;
        this.customerName = dto.customerName;
        this.addressLine1 = dto.addressLine1;
        this.addressLine2 = dto.addressLine2;
        this.addressLine3 = dto.addressLine3;
        this.addressLine4 = dto.addressLine4;
        this.zipCode5 = dto.zipCode5;
        this.zipCode9 = dto.zipCode9;
        this.zipCode14 = dto.zipCode14;
        this.totalDue = dto.totalDue;
        this.currentDue = dto.currentDue;
        this.overdue1To10Days = dto.overdue1To10Days;
        this.overdue11To20Days = dto.overdue11To20Days;
        this.overdue21To30Days = dto.overdue21To30Days;
        this.overdueOver30Days = dto.overdueOver30Days;
        this.lastPaymentAmount = dto.lastPaymentAmount;
        this.lastPaymentDate = dto.lastPaymentDate;
        this.prepaidAmount = dto.prepaidAmount;
        this.monthToDateSales = dto.monthToDateSales;
        this.yearToDateSales = dto.yearToDateSales;
        this.statementFlag = dto.statementFlag;
        this.financialAdjustmentFlag = dto.financialAdjustmentFlag;
        this.previousBalance = dto.previousBalance;
        this.financialIncrease = dto.financialIncrease;
        this.monthlyCreditPeriod = dto.monthlyCreditPeriod;
        this.yearlyCreditPeriod = dto.yearlyCreditPeriod;
        this.creditLimit = dto.creditLimit;
        this.areaCode = dto.areaCode;
        this.telephoneNumber = dto.telephoneNumber;
        this.salesPersonNumber = dto.salesPersonNumber;
        this.termsCode = dto.termsCode;
        this.stateTaxCode = dto.stateTaxCode;
        this.lastTransactionNumber = dto.lastTransactionNumber;
        this.groupCode = dto.groupCode;
        this.miles = dto.miles;
        this.highBalance = dto.highBalance;
        this.highBalanceDate = dto.highBalanceDate;
        this.interestRate = dto.interestRate;
        this.accountStatus = dto.accountStatus;
        this.referenceNumber = dto.referenceNumber;
        this.groupCompany = dto.groupCompany;
        this.groupCustomerNumber = dto.groupCustomerNumber;
        this.paymentDate8Digit = dto.paymentDate8Digit;
        this.highBalanceDate8Digit = dto.highBalanceDate8Digit;
        this.customerClass = dto.customerClass;
        this.ediIndicator = dto.ediIndicator;
        this.closeBalance = dto.closeBalance;
        this.wireTransferFlag = dto.wireTransferFlag;
        this.federalEIN = dto.federalEIN;
        this.paymentClass = dto.paymentClass;
        this.promotionalCode = dto.promotionalCode;
        this.reservedField1 = dto.reservedField1;
    }
}
